config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :showings

  resources :tickets

  resources :movies

  resources :theatres

  root 'pages#homepage'

end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
	has_many:showings
	
	validates :theatreName, presence: true
	validates :location, presence: true
	validates :capacity, presence: true

end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: [:show, :edit, :update, :destroy]

  # GET /theatres
  # GET /theatres.json
  def index
    @theatres = Theatre.all
  end

  # GET /theatres/1
  # GET /theatres/1.json
  def show
      @showings = Showing.all
  end

  # GET /theatres/new
  def new
    @theatre = Theatre.new
  end

  # GET /theatres/1/edit
  def edit
  end

  # POST /theatres
  # POST /theatres.json
  def create
    @theatre = Theatre.new(theatre_params)

    respond_to do |format|
      if @theatre.save
        format.html { redirect_to @theatre, notice: 'Theatre was successfully created.' }
        format.json { render :show, status: :created, location: @theatre }
      else
        format.html { render :new }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theatres/1
  # PATCH/PUT /theatres/1.json
  def update
    respond_to do |format|
      if @theatre.update(theatre_params)
        format.html { redirect_to @theatre, notice: 'Theatre was successfully updated.' }
        format.json { render :show, status: :ok, location: @theatre }
      else
        format.html { render :edit }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1
  # DELETE /theatres/1.json
  def destroy
    @theatre.destroy
    respond_to do |format|
      format.html { redirect_to theatres_url, notice: 'Theatre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre
      @theatre = Theatre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theatre_params
      params.require(:theatre).permit(:theatreName, :location, :capacity)
    end
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/theatres/_form.html.erb
<%= form_for(@theatre) do |f| %>
  <% if @theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theatre.errors.count, "error") %> prohibited this theatre from being saved:</h2>

      <ul>
      <% @theatre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :theatreName %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theatres/edit.html.erb
<h1>Editing theatre</h1>

<%= render 'form' %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

app/views/theatres/index.html.erb
<h1>Listing theatres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theatres.each do |theatre| %>
		  <tr>
			<td><%= theatre.theatreName %></td>
			<td><%= theatre.location %></td>
			<td><%= theatre.capacity %></td>
			<td><%= link_to 'Show', theatre %></td>
			<td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
			<td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theatre', new_theatre_path %>

app/views/theatres/new.html.erb
<h1>New theatre</h1>

<%= render 'form' %>

<%= link_to 'Back', theatres_path %>

app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theatre.theatreName %>
</p>

<p>
  <strong>Location:</strong>
  <%= @theatre.location %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @theatre.capacity %>
</p>


<%= link_to 'Edit', edit_theatre_path(@theatre) %> |
<%= link_to 'Back', theatres_path %>